### ISSUE TITLE
为什么要先查一下 lmr

### ISSUE THREAD

**Issue by Kherrisan** [TheColdVoid/nbnhhsh-alfred-workflow#1]
query.py : 43

```
queryTrans('lmr')
```
是多余的吧

**Comment by TheColdVoid** [comment]
@Kherrisan 
嗯嗯谢谢您的提醒，这行确实是我之前测试时候写的临时语句，忘记删除了。
现已删除这行无用调用https://github.com/TheColdVoid/nbnhhsh-alfred-workflow/commit/2013654b7f09c4d0d94aeae626b28d7f20e342e2
也更新了打包后的workflow文件：
https://github.com/TheColdVoid/nbnhhsh/raw/master/nbnhhsh.alfredworkflow
